// LumiScript — ESLint flat config (roadmap #10, first increment).
//
// Deliberately MINIMAL. We do NOT pull in the full recommended-type-checked
// rule set — that would dump hundreds of findings on an existing codebase and
// demand a giant one-time cleanup. Instead we enable only the two async-safety
// rules that the rc.8 "async handler wrappers MUST await" fix was about:
// floating promises and promises misused in sync (void-expecting) positions.
// These are type-aware (need `projectService`) and catch a real bug class that
// `tsc` does not. Grow the rule set incrementally in later increments.
//
// NOTE: `@typescript-eslint/await-thenable` is deliberately NOT enabled. Our
// handler-wrapper pattern intentionally `await`s a user handler typed `void`
// (which legally accepts a `Promise<void>`); that await is the rc.8 fix — it
// keeps the handler-IPC run alive across an async handler. await-thenable would
// flag those awaits as "awaiting a non-Promise" and pressure their removal,
// reintroducing the dropped-dispatch bug. See api-proxy.ts (`await handler(...)`).
//
// Scope: src/** only for now (tests have intentional floating promises, e.g.
// unhandled-rejection-guard.test.ts). The generated corpus + build output are
// ignored.

import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'src/assistant/corpus/**', // generated by gen:corpus (huge, machine-written)
      'bench/**',
      'scripts/**',
    ],
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: { '@typescript-eslint': tseslint.plugin },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-floating-promises': 'error',
      // `checksVoidReturn` is disabled for this increment: it flags idiomatic
      // async handlers passed to void-returning callbacks (React on* event
      // handlers, `onFrontendMessage`/`onBackendMessage` subscribers) which the
      // framework intentionally fire-and-forgets. Wrapping each in `() => void
      // f()` silences without adding safety. The high-value bug class — a
      // floating promise, INCLUDING inside those handlers (the rc.8 class) — is
      // fully covered by `no-floating-promises` above. We keep this rule's
      // `checksConditionals` + `checksSpreads` (genuine bugs: a promise used in
      // an `if`/`&&`/spread). Revisit checksVoidReturn (with a per-handler
      // error-handling audit) in a later increment.
      '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: false }],
    },
  },
);
