/**
 * ============================================================================
 * LUMISCRIPT — SCRIPT-RUNNER IPC TYPES
 * ============================================================================
 * Discriminated union types for messages exchanged between the LumiScript
 * main backend (parent) and the script-runner child subprocess.
 *
 * Convention mirrors `messages.ts`: every message has a `type` field as the
 * discriminant on both sides.
 *
 * Shared between parent and child — drift between the two implementations
 * is caught at typecheck time as long as both sides import from this file.
 *
 * Architecture context: see `notes/step-2-design.md`.
 *
 * ─── Direction notation ─────────────────────────────────────────────────────
 *   Parent → Child:   `ParentToChildMessage` (this file's first union)
 *   Child  → Parent:  `ChildToParentMessage` (second union)
 *
 * Naming convention:
 *   - Request types end with `-request` and expect a corresponding response
 *   - Notice types end with `-notice` and are fire-and-forget
 *   - Lifecycle messages use plain past-tense verbs (`run-result`, etc.)
 *
 * ─── Correlation IDs ────────────────────────────────────────────────────────
 *   `runId`        Unique per script execution. Generated by the parent at
 *                  run-dispatch time. Used to scope transient handles, route
 *                  console output, and identify the active script in error
 *                  reporting.
 *   `requestId`    Unique per api proxy call. Generated by the child at
 *                  call time. Used to correlate ApiProxyRequest with
 *                  ApiProxyResponse and to target AbortRequest.
 *   `subId`        Unique per broadcast subscription. Generated by the
 *                  child at subscribe time.
 */

import type {
  ConsoleEntry,
  ScriptType,
  MacroDefinition,
  ToolDefinition,
  MacroInterceptorOptions,
  MessageContentProcessorOptions,
  WorldInfoInterceptorOptions,
  MessageTagOptions,
  DOMListenOptions,
  DOMDelegateOptions,
  AdvancedModalDismissReason,
  RegisteredToolInfo,
  RegisteredMacroInfo,
  RegisteredMacroInterceptorInfo,
  InjectionInfo,
  RegisteredMessageContentProcessorInfo,
  RegisteredWorldInfoInterceptorInfo,
} from './script.js';

// ─── Shared shapes ──────────────────────────────────────────────────────────

/**
 * Opaque identifier for a host-resident object (e.g. a `Collection` returned
 * by `api.db.collection`, a `DOMHandle` returned by `api.ui.dom.injectAtMessage`).
 * The child receives this in place of the real object and uses it in subsequent
 * api calls that target the underlying object.
 */
export type HandleId = string;

/**
 * Wire format for a host-resident object handle. Sent from parent to child
 * as the result of api calls that return objects with methods. The child's
 * proxy generator uses `kind` to pick the correct proxy class to wrap the
 * returned reference.
 *
 * Transient handles (e.g. `Collection`) are dropped on script-run completion.
 * Persistent handles (e.g. `DOMHandle`, `RegisteredMacroHandle`) are tied to
 * the owning script's lifecycle via the existing `clearByScriptId` patterns.
 * The lifecycle classification lives in the dispatcher, not on the wire.
 */
export interface HandleRef {
  __handleRef: true;
  id: HandleId;
  kind: HandleKind;
}

/**
 * Stable identifiers for the categories of host-resident objects that can
 * be exposed to the child as handles. Each kind has a corresponding proxy
 * class on the child that knows how to dispatch method calls.
 */
export type HandleKind =
  | 'Collection'
  | 'DOMHandle'
  | 'CollapsibleDOMHandle'
  | 'ProgressBarHandle'
  | 'RegisteredMacroHandle'
  | 'RegisteredToolHandle'
  | 'RegisteredDrawerTab'
  | 'RegisteredInputBarAction'
  | 'RegisteredCommandHandle'
  | 'RegisteredFloatWidget'
  | 'BroadcastSubscription'
  | 'MacroInterceptorHandle'
  | 'ContentProcessorHandle'
  | 'StyleHandle'
  | 'EnclaveHandle'
  | 'MountedComponent';

/**
 * Serialised form of a thrown error. Errors don't survive structured-clone
 * intact across IPC boundaries, so we capture name/message/stack explicitly.
 */
export interface SerializedError {
  name:    string;
  message: string;
  stack?:  string;
}

// ─── Parent → Child ─────────────────────────────────────────────────────────

/**
 * Parent dispatching a script run to the child. Carries everything the child
 * needs to execute the script body in its sandbox: code, trigger event data,
 * granted permissions, timeout, and identity (script + run + user).
 *
 * The child responds with a `RunResult` once execution completes (success or
 * error). During the run, the child may emit any number of `ApiProxyRequest`,
 * `BroadcastSubscribeMessage`, `BroadcastUnsubscribeMessage`, `AbortRequest`,
 * `ScriptRunningNotice`, and `ConsoleEntryNotice` messages.
 */
export interface RunScriptRequest {
  type:               'run-script';
  runId:              string;
  scriptId:           string;
  scriptName:         string;
  /**
   * The script's declared type — exposed to user code as `script.type`. The
   * dispatcher copies this directly from the real `Script.type` field
   * (no synth-shim hardcoding from Phase 7's prototype).
   */
  scriptType:         ScriptType;
  /** The user-script source to execute. */
  code:               string;
  /** The trigger event payload (e.g. MESSAGE_SENT data) — passed as `data` to the AsyncFunction. */
  data:               unknown;
  /** Async timeout window. The existing Promise.race in executor.ts moves to the child. */
  timeoutMs:          number;
  /** Permissions granted to the LumiScript extension (NOT per-script — see lumiscript_permission_model.md). */
  grantedPermissions: string[];
  /** User ID for operator-scoped api calls. Optional in single-user mode. */
  userId?:            string;
  /** Whether the script has the `allowDangerous` flag (gates http etc.). */
  allowDangerous:     boolean;
  /**
   * #11 — which sandbox engine runs the user body: `'asyncfn'` (the
   * `new AsyncFunction` path, default) or `'quickjs'` (the QuickJS-WASM
   * isolate). Optional for forward-compat with older parents; the child
   * defaults to `'asyncfn'` when unset.
   */
  engineMode?:        'asyncfn' | 'quickjs';
  /**
   * Phase 9d.1 — snapshot of the active chat / character ID at run-dispatch
   * time. Used by the child to implement sync-returning api methods like
   * `api.chat.getChatId()` locally without an IPC roundtrip.
   *
   * For trigger fires this matches the chat that triggered the event;
   * activeContext doesn't change mid-run so the snapshot is correct.
   * Long-lived registered handlers (Phase 9d.3) will need a different
   * pattern — when a registered macro's handler fires from a different
   * chat than the one it was registered in, the live activeContext on the
   * parent already gives the right chatId for THAT call. Phase 9d.3's
   * design will surface chatId per-handler-invocation, not per-script-run.
   */
  chatIdAtStart?:      string | null;
  characterIdAtStart?: string | null;
  /**
   * Phase 9d.X — snapshots of sync-array-read surfaces at run-dispatch time.
   * Lets the child's proxy implement `api.tools.list()`, `api.macros.list()`,
   * `api.macros.listInterceptors()`, `api.chat.getInjections()`, and
   * `api.chat.listContentProcessors()` synchronously (matching the canonical
   * sync return contract) without an IPC roundtrip per call.
   *
   * The proxy maintains these arrays AS MUTABLE per-run state — register /
   * unregister / inject / removeInjection mutations update the local array
   * eagerly, so user code that does `api.tools.register(...); api.tools.list()`
   * within a single run sees the just-registered tool (matching canonical
   * sync semantics exactly). Cross-script mutations during the same run
   * are NOT reflected (snapshot is dispatch-time + this-script-only diffs);
   * an acceptable best-effort approximation for diagnostic surfaces.
   */
  toolsSnapshot?:                 RegisteredToolInfo[];
  macrosSnapshot?:                RegisteredMacroInfo[];
  macroInterceptorsSnapshot?:     RegisteredMacroInterceptorInfo[];
  chatInjectionsSnapshot?:        InjectionInfo[];
  chatContentProcessorsSnapshot?: RegisteredMessageContentProcessorInfo[];
  /** v0.27.0+ — pre-existing world-info interceptor entries owned by this script. */
  worldInfoInterceptorsSnapshot?: RegisteredWorldInfoInterceptorInfo[];
}

/**
 * Parent's response to an `ApiProxyRequest`. Carries either the resolved
 * value (which may be a `HandleRef` for object-returning methods) or a
 * `SerializedError` if the underlying api call rejected.
 */
export interface ApiProxyResponse {
  type:      'api-response';
  requestId: string;
  ok:        boolean;
  /** Present when `ok === true`. May be a primitive, plain object, or HandleRef. */
  value?:    unknown;
  /** Present when `ok === false`. */
  error?:    SerializedError;
}

/**
 * Parent forwarding a broadcast event firing to the child. The parent owns
 * the bus; child maintains a handler registry keyed by (scriptId, subId).
 * On receipt, the child looks up the closure and invokes it with `payload`.
 */
export interface BroadcastFireMessage {
  type:     'broadcast-fire';
  scriptId: string;
  subId:    string;
  event:    string;
  payload:  unknown;
}

/**
 * Parent telling the child to drop all broadcast subscription handlers
 * owned by `scriptId`. Mirrors the existing `clearBroadcastByScriptId`
 * pattern in the parent's broadcast-bus, applied at the start of every
 * new trigger run for that script. The lifecycle invariant — subscriptions
 * persist BETWEEN runs, wiped at the start of the next run — is preserved.
 */
export interface BroadcastClearMessage {
  type:     'broadcast-clear';
  scriptId: string;
}

/**
 * Graceful-shutdown signal. Parent sends this to ask the child to drain
 * in-flight work and exit cleanly. Used during LumiScript teardown
 * (extension disable / unload). The child responds by calling
 * `process.complete()` when it has nothing else to do; the host then
 * tears down the subprocess.
 *
 * Distinct from a hard kill: hard kills come from the host (SIGKILL on
 * heartbeat timeout) and don't go through this channel.
 */
export interface ShutdownRequest {
  type: 'shutdown';
}

/**
 * Phase 9d.3 — kind discriminator for function-handler registrations
 * (`api.macros.register`, `api.tools.register`, etc.). Used by the
 * `RegisterHandler` / `UnregisterHandler` / `RunHandlerRequest` envelopes
 * to dispatch to the correct parent-side store and select the correct
 * arg-shape on the child when invoking the user's closure.
 */
export type HandlerKind =
  | 'macro'                  // 9d.3.a — pull-mode MacroHandler
  | 'tool'                   // 9d.3.b — ToolHandler
  | 'commandsOnInvoked'      // 9d.3.c
  | 'contentProcessor'       // 9d.3.d
  | 'macroInterceptor'       // 9d.3.d
  | 'worldInfoInterceptor'   // v0.27.0 — api.worldInfo.registerInterceptor() handler
  | 'messageTagHandler'      // v1.4 — api.chat.onMessageTag() message-tag interceptor
  | 'domEventListener'       // 9d.4.c-2 — DOMHandle.on() event handler
  | 'domDelegate'            // v0.27.1 — api.ui.dom.delegate() event-delegated handler
  | 'inputBarActionClick'    // 9d.4.e-1-b — InputBarActionHandle.onClick() click handler
  | 'floatWidgetDragEnd'     // 9d.4.e-2-b — FloatWidgetHandle.onDragEnd() drag-end handler
  | 'drawerTabActivate'      // 9d.4.e-3-b — DrawerTabHandle.onActivate() activation handler
  | 'rpc'                    // v0.26.0 — api.rpc.handle() on-demand handler (cross-extension RPC pool)
  | 'oauthCallback'          // v1.0.0-rc.5 — api.oauth.onCallback() inbound-HTTP callback handler
  | 'componentCallback'      // v1.0.0-rc.9 — api.ui.components.* mount-option callbacks (onChange, etc.)
  | 'uiKeyboardChange'       // v1.0.0-rc.9 — api.ui.events.onKeyboardChange() subscription
  | 'uiDrawerChange'         // v1.0.0-rc.9 — api.ui.events.onDrawerChange() subscription
  | 'uiSettingsChange';      // v1.0.0-rc.9 — api.ui.events.onSettingsChange() subscription

/**
 * Phase 9d.3 — parent firing a registered handler. The child looks up
 * the handler by `(scriptId, handlerId)`, runs it inside an
 * AsyncLocalStorage context that overrides the proxy's `runId` for any
 * api.* calls the handler makes, sends back `HandlerResult`.
 *
 * Handler args are JSON-cloneable per-kind contexts (`MacroContext`,
 * `MacroInterceptorCtx`, etc.). For tool handlers, `api` is NOT in the
 * args — it gets injected by the child runtime from the per-script proxy.
 */
export interface RunHandlerRequest {
  type:        'run-handler';
  /**
   * Fresh per-fire `runId`. The parent registers a minimal `activeRun`
   * entry under this id for the duration of the handler call so the
   * child's `dispatch` (now AsyncLocalStorage-keyed for `runId`) routes
   * back to the right api.
   */
  runId:       string;
  scriptId:    string;
  handlerId:   string;
  kind:        HandlerKind;
  /** Per-kind handler arguments. JSON-cloneable. */
  args:        unknown[];
  /** Async-loop timeout for this handler invocation (mirrors RunScriptRequest.timeoutMs). */
  timeoutMs:   number;
  /**
   * Live activeContext snapshot taken at handler-fire time (parent-side, from
   * `binding.ts`). Used by the child to override sync getters
   * (`api.chat.getChatId()`, future symmetric `characterId` getters) for
   * the duration of this handler invocation via a per-fire AsyncLocalStorage
   * scope (`liveContextStore.run(...)` in `child-entry.ts`).
   *
   * Why this exists: without these fields, the child's sync getters fall
   * back to `ctx.chatIdAtStart` / `ctx.characterIdAtStart` — values
   * snapshotted at SCRIPT-LOAD time and never refreshed. Long-lived
   * handlers (widget click, modal `onDismiss`, drawer-tab `onActivate`,
   * input-bar `onClick`, tool fires, etc.) that run after the user has
   * switched chats would otherwise see stale `null`s. Closes the residual
   * the v0.23.2 stale-active-context fix left on the sync-API path.
   */
  chatIdAtFire:      string | null;
  characterIdAtFire: string | null;
}

/**
 * Phase 9d.3 — child returning the result of a handler fire. Mirrors
 * `RunScriptResult`'s envelope but routed to the wrapper closure that
 * lives in the parent's per-handler `pendingHandlerCalls` map.
 */
export interface HandlerResult {
  type:       'handler-result';
  runId:      string;
  ok:         boolean;
  value?:     unknown;
  error?:     SerializedError;
  durationMs: number;
}

/**
 * Phase 9d.3 — parent telling the child to drop ALL handler closures and
 * the proxy belonging to a script. Sent on script-unregister (extension
 * disable, script delete, etc.). Mirrors `BroadcastClearMessage` in
 * scope but covers the function-handler registry too.
 */
export interface ScriptUnregisterMessage {
  type:     'script-unregister';
  scriptId: string;
}

/**
 * Phase 9d.4.e-2-b — parent notifying the child that a float widget's
 * frontend-cached position has changed via a user drag. Fires once per
 * `ls_float_widget_drag_end` echo from the FE, BEFORE any user-registered
 * `onDragEnd` handlers are dispatched (handlers ride the standard
 * register-handler IPC path). This ordering guarantees that a user's
 * `onDragEnd` callback observing `handle.getPosition()` sees the new
 * position synchronously inside the callback.
 *
 * Independent of registration: even when zero `onDragEnd` handlers are
 * registered, the notice keeps `getPosition()` accurate after a drag.
 *
 * Programmatic position changes (`handle.moveTo`) update the proxy's
 * `positionCache` synchronously and don't go through this path — the
 * notice exists specifically to bridge FE-driven position changes back
 * into child-side state.
 */
export interface FloatWidgetPositionNotice {
  type:     'float-widget-position';
  widgetId: string;
  x:        number;
  y:        number;
}

/**
 * Phase 9d.4.d — parent notifying the child that a previously-opened
 * advanced modal has been dismissed (user click, script call, or teardown).
 *
 * Bus-like fire-and-forget pattern: the parent registers ONE internal
 * `onDismiss` listener with the canonical handle when `showAdvancedModal`
 * fires, and on dismissal sends this notice to the child. The child's
 * api-proxy module-scope `advancedModalState` table looks up the modalId,
 * flips its cached `dismissed` flag, and invokes all locally-stored user
 * listeners (the closures registered via `handle.onDismiss(fn)`).
 *
 * This avoids the alternative of one `register-handler` IPC per
 * `onDismiss(fn)` call — a script that registers ten handlers on the same
 * modal pays for ten parent-side wrapper closures + the matching
 * `unregister-handler` storms when they're dropped. The bus pattern is one
 * IPC per modal lifecycle, regardless of listener count.
 */
export interface AdvancedModalDismissedNotice {
  type:    'advanced-modal-dismissed';
  modalId: string;
  reason:  AdvancedModalDismissReason;
}

/**
 * Parent asking the child to report its own process resource usage. Used by
 * the v0.28.0+ diagnostics panel to surface script-runner subprocess health
 * (RSS, heap, CPU time) without adding host-side periodic instrumentation.
 *
 * Child responds with `DiagnosticStatsResponse` carrying the same requestId.
 * Parent times the request out via the diagnostic-collector's caller — no
 * timeout enforcement on this end; if the child is hung the response simply
 * never arrives and the collector falls back to "not available".
 */
export interface DiagnosticStatsRequest {
  type:      'diagnostic-stats-request';
  requestId: string;
}

/**
 * v1.0.0-rc.6 — per-script state snapshot the parent sends to a child worker
 * when a script first dispatches to that worker (cold spawn OR post-respawn
 * OR post-rebalance reassignment). Lets the child pre-populate proxy-side
 * stable-id caches that would otherwise diverge from the parent's view.
 *
 * Empty fields MUST be omitted (not sent as `{}`); consumers treat an
 * absent field as "no state to seed for that surface". The child tolerates
 * unknown top-level keys for forward-compat — newer parents can extend the
 * snapshot without breaking older child builds.
 *
 * ─── Why this exists ───────────────────────────────────────────────────────
 *
 * Eviction asymmetry: parent-side persistent state (dom-registry, etc.)
 * survives worker death; child-side caches (api-proxy module-scope maps)
 * die with the worker. Without seeding, the proxy's child-side cache
 * regenerates IDs from scratch post-respawn while the parent's view still
 * holds the original ones — same stable identifier maps to two different
 * elementIds across the lifetime asymmetry boundary.
 *
 * The v1.0.0-rc.3 alias-storage hotfix in `handleDomInjectRequest` papers
 * over the divergence by storing handles under BOTH the canonical id and
 * the proxy's regenerated id; this snapshot replaces that hotfix with the
 * architecturally clean approach (child snapshots state from parent on
 * bootstrap, single source of truth). Keeping the hotfix in place as
 * belt-and-suspenders until state-sync burns in for a release or two.
 *
 * ─── Inventory of caches today (rc.6) ─────────────────────────────────────
 *
 * Only `domStableIdToElementId` needs syncing. Other proxy-side maps
 * (`advancedModalState`, `floatWidgetState`, `latestRunIdByScript`) don't
 * carry cross-respawn stable-id idempotency semantics — modals / widgets
 * are per-creation entities without a user-supplied stableId mapping, and
 * the run-id tracker is runtime routing state that re-establishes on each
 * dispatch.
 */
export interface ScriptStateSnapshot {
  scriptId: string;
  /**
   * `stableId → elementId` for every DOM element this script has injected
   * with a user-supplied stable ID. Omitted when the script has no
   * stable-id-tagged elements (the common case at startup).
   */
  domStableIds?: Record<string, string>;
}

/**
 * Parent → child message carrying a `ScriptStateSnapshot` for a script
 * about to dispatch on this worker. Sent BEFORE the corresponding
 * `RunScriptRequest` (Bun IPC is FIFO per channel, so ordering is
 * guaranteed without an ack handshake).
 *
 * Idempotent on receipt: applying the same snapshot twice is a no-op.
 * Empty snapshots are not sent (parent gates on `hasContent`).
 */
export interface ScriptStateSyncMessage {
  type:     'script-state-sync';
  snapshot: ScriptStateSnapshot;
}

export type ParentToChildMessage =
  | RunScriptRequest
  | ApiProxyResponse
  | StreamChunkMessage
  | StreamEndMessage
  | BroadcastFireMessage
  | BroadcastClearMessage
  | RunHandlerRequest
  | ScriptUnregisterMessage
  | AdvancedModalDismissedNotice
  | FloatWidgetPositionNotice
  | DiagnosticStatsRequest
  | ScriptStateSyncMessage
  | ShutdownRequest;

// ─── Child → Parent ─────────────────────────────────────────────────────────

/**
 * Child notifying parent that it has begun executing a specific script run.
 * Sent immediately before invoking the user's AsyncFunction body; lets the
 * parent track the active script so a subsequent host-driven SIGKILL (on
 * missed heartbeat) can be surfaced with the offending script name.
 */
export interface ScriptRunningNotice {
  type:       'script-running';
  runId:      string;
  scriptId:   string;
  scriptName: string;
  startedAt:  number;
}

/**
 * Child returning the result of a completed script run. Either a value
 * (typically `undefined` — most user scripts run for side effects) or a
 * serialized error. Mirrors the shape of the existing `executeScript`
 * return value, just delivered over IPC instead of a function return.
 */
export interface RunScriptResult {
  type:        'run-result';
  runId:       string;
  scriptId:    string;
  ok:          boolean;
  value?:      unknown;
  error?:      SerializedError;
  /** Wall-clock execution duration in ms; measured inside the child. */
  durationMs:  number;
}

/**
 * Child invoking a method on the parent's api surface. Either targets the
 * top-level api (`targetHandle === undefined`, `method` is a dotted path
 * like `db.collection` or `chat.getMessages`) or a specific handle's method
 * (`targetHandle` is the HandleRef, `method` is just the method name).
 *
 * Args may contain `HandleRef` values when the user passed a handle as an
 * argument (e.g., `await collection.find()` where `collection` is a handle).
 *
 * `hasSignal` is `true` when the original call passed `opts.signal` —
 * the child stores the AbortSignal locally and emits `AbortRequest` if the
 * signal aborts before the response arrives.
 */
export interface ApiProxyRequest {
  type:          'api-request';
  requestId:     string;
  /** Run scope — used by the dispatcher for permission checks and transient-handle scoping. */
  runId:         string;
  scriptId:      string;
  /** Either a dotted-path on the top-level api, or a method name when `targetHandle` is set. */
  method:        string;
  args:          unknown[];
  /** Present when invoking a method on a previously-returned object handle. */
  targetHandle?: HandleRef;
  /** True if `opts.signal` was supplied; child may emit AbortRequest later. */
  hasSignal?:    boolean;
  /**
   * v0.26.1 — diagnostic-only. Records which of the proxy's three-tier
   * runId-resolution fallbacks produced `runId` at dispatch time:
   *
   *   - `'context'`  — `runIdContext.getStore()` (AsyncLocalStorage). Dispatch
   *     was issued inside a handler-fire (`runIdContext.run(handler-…, …)`)
   *     OR inside the script body wrapped by AsyncLocalStorage propagation.
   *   - `'latest'`   — `latestRunIdByScript.get(scriptId)`. Dispatch was
   *     issued OUTSIDE any runIdContext.run, falling through to the per-
   *     script latest-run map. Typical for cross-run handle method calls
   *     and detached IIFEs from broadcast handlers.
   *   - `'ctx'`      — the originating proxy's `ctx.runId`. Reached only
   *     when no runIdContext is active AND latestRunIdByScript hasn't
   *     been populated (essentially defensive — should be very rare).
   *
   * Surfaced in the parent's `RunCompletedError` message when a late
   * dispatch arrives, so post-mortem analysis can pin the leak class
   * without re-instrumenting the proxy. Optional — older parents that
   * don't read this field are forward-compatible (the parent treats
   * `undefined` as "unknown source").
   */
  _runIdSource?: 'context' | 'latest' | 'ctx';
}

/**
 * Child requesting the parent to abort an in-flight `ApiProxyRequest`.
 * Triggered by the user-script's `AbortController.abort()` firing on a
 * signal that was passed to a proxy method.
 *
 * Parent's dispatcher calls `controller.abort()` on the real api call;
 * the api rejects with `AbortError` per its existing semantics; parent
 * sends back an `ApiProxyResponse { ok: false, error }`.
 *
 * Idempotent: repeated aborts for the same `requestId` are no-ops.
 */
export interface AbortRequest {
  type:      'abort-request';
  requestId: string;
}

/**
 * Child requesting a streaming api call (v1.0.0-rc.9 — currently only
 * `'llm.generateStream'`). Wire-shape mirrors `ApiProxyRequest` but the
 * parent answers with zero-or-more `StreamChunkMessage` followed by a
 * single terminal `StreamEndMessage`, rather than a single `ApiProxyResponse`.
 *
 * `hasSignal` reuses the existing `AbortController`/`AbortRequest` plumbing
 * — the parent injects a signal into the request options and the child's
 * `AbortSignal` is wired to emit `AbortRequest` on abort.
 *
 * Cancellation paths beyond AbortSignal:
 *   - Consumer breaks out of the `for await` loop → child sends
 *     `StreamCancelRequest`. Parent calls `.return()` on the upstream
 *     iterator, propagating teardown to the underlying HTTP request.
 *   - Run ends / script torn down → parent sweeps any open streams owned
 *     by the affected run + sends final `StreamEndMessage { ok: false }`.
 */
export interface StreamRequest {
  type:          'stream-request';
  requestId:     string;
  runId:         string;
  scriptId:      string;
  /** Currently only `'llm.generateStream'`. Forward-extensible if other streaming methods are added later. */
  method:        string;
  args:          unknown[];
  /** True if `opts.signal` was supplied; child may emit `AbortRequest` later. Same semantics as `ApiProxyRequest.hasSignal`. */
  hasSignal?:    boolean;
  /** v0.26.1 — diagnostic-only. Same three-tier resolution as `ApiProxyRequest._runIdSource`. See that field's JSDoc. */
  _runIdSource?: 'context' | 'latest' | 'ctx';
}

/**
 * Parent forwarding one chunk from the upstream `spindle.generate.rawStream`
 * iterator. The `chunk` payload is structurally a `StreamChunk` from
 * `src/types/script.ts` — the boundary leaves it as `unknown` so this IPC
 * type doesn't take a dependency on the user-facing surface.
 */
export interface StreamChunkMessage {
  type:      'stream-chunk';
  requestId: string;
  chunk:     unknown;
}

/**
 * Parent signalling the end of a stream. Exactly one of these per
 * `StreamRequest`, after zero-or-more `StreamChunkMessage`s.
 *
 *   - `ok: true`  — upstream iterator completed normally. No `error`.
 *   - `ok: false` — upstream rejected, consumer aborted, or run ended
 *     mid-stream. `error` carries the serialized failure.
 */
export interface StreamEndMessage {
  type:      'stream-end';
  requestId: string;
  ok:        boolean;
  /** Present when `ok === false`. */
  error?:    SerializedError;
}

/**
 * Child telling the parent that the consumer's `for await` loop ended
 * before the stream did — typically a `break`, a `throw` propagating out
 * of the loop body, or the loop's caller throwing. Parent calls `.return()`
 * on the upstream iterator to tear down the in-flight HTTP request.
 *
 * Distinct from `AbortRequest`, which represents an external `AbortSignal`
 * firing. Both end the stream; cancel is the cooperative path, abort the
 * imperative one. Idempotent — repeated cancels for the same requestId
 * are no-ops.
 */
export interface StreamCancelRequest {
  type:      'stream-cancel';
  requestId: string;
}

/**
 * Child registering a broadcast subscription on the parent. The handler
 * itself stays in the child's registry; the parent records only the
 * subscription metadata and forwards firings via `BroadcastFireMessage`.
 *
 * Lifecycle: subscriptions persist between trigger runs of the owning
 * script and are cleared by the parent's `clearBroadcastByScriptId` (sent
 * to the child as `BroadcastClearMessage` at the start of every new run).
 */
export interface BroadcastSubscribeMessage {
  type:     'broadcast-subscribe';
  scriptId: string;
  subId:    string;
  event:    string;
}

/**
 * Child explicitly unsubscribing from a broadcast event. Triggered by the
 * user calling the unsubscribe function returned by `api.broadcast.on()`.
 * Distinct from the bulk `BroadcastClearMessage` which clears all of a
 * script's subscriptions.
 */
export interface BroadcastUnsubscribeMessage {
  type:     'broadcast-unsubscribe';
  scriptId: string;
  subId:    string;
}

/**
 * Child forwarding a `console.*` call from a user script up to the parent.
 * Reuses the existing `ConsoleEntry` shape from `script.ts` so the parent
 * can pass it through to the frontend's console pane unchanged.
 */
export interface ConsoleEntryNotice {
  type:     'console-entry';
  runId:    string;
  scriptId: string;
  entry:    ConsoleEntry;
}

/**
 * Phase 9d.3 — child registering a function-handler with the parent. Each
 * `api.macros.register` / `api.tools.register` / etc. call from user
 * script code dispatches one of these (sync void from the user's
 * perspective; the IPC is fire-and-forget). The parent builds a wrapper
 * closure that, when invoked by the host's macro engine / tool dispatch
 * / etc., sends `RunHandlerRequest` back to the child + awaits the
 * `HandlerResult`.
 *
 * Discriminated union by `kind`. The shape carries any per-kind metadata
 * the parent's store needs (macro name + def, tool name + def, etc.).
 *
 * `runId` is the script run that's currently executing user code; used
 * by the parent to look up the active run's tracking sets / api object
 * for stale-diff cleanup at run-end.
 */
export type RegisterHandler =
  | {
      type:      'register-handler';
      kind:      'macro';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      name:      string;
      def:       MacroDefinition;
      /** `false` = push-mode (no real handler closure); the IPC is just
       *  for shape consistency in 9d.3.a, since `macros.register` without
       *  a handler still hits the same registration path. The child won't
       *  send `register-handler` for push-mode at all — it dispatches via
       *  the existing `dispatch('macros.register', …)` passthrough. This
       *  field is reserved for 9d.3.b+ when other kinds may need it. */
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'tool';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      name:      string;
      def:       ToolDefinition;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'commandsOnInvoked';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      // No `name`, no `def` — `commands.onInvoked(handler)` is a single
      // global callback per script. Auto-unsubs any prior handler for the
      // same script before registering (canonical behaviour, mirrored on
      // the parent side via `clearCommandHandlerByScriptId`).
      hasHandler: true;
    }
  // v1.0.0-rc.9 — api.ui.events.on{Keyboard,Drawer,Settings}Change subscriptions.
  // Same shape as commandsOnInvoked (no per-handle id); the fired handler
  // receives the changed UI state as its single arg. Multiple subscriptions
  // per script per channel are allowed (each gets a distinct handlerId).
  | {
      type:      'register-handler';
      kind:      'uiKeyboardChange';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'uiDrawerChange';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'uiSettingsChange';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'macroInterceptor';
      runId:     string;
      scriptId:  string;
      // The child generates the handlerId AND uses it as the canonical
      // entry id. The parent forwards via `options.id = handlerId` to
      // `addInterceptorEntry`, which stores under `compositeKey(scriptId, id)`.
      // User-supplied options.id (if any) is preserved on the child side
      // and overrides the auto-generated handlerId. Result: the handle's
      // `.id` returned synchronously to user code matches what's stored
      // parent-side, so subsequent `handle.remove()` lookups work.
      handlerId: string;
      options?:  MacroInterceptorOptions;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'contentProcessor';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      options?:  MessageContentProcessorOptions;
      hasHandler: true;
    }
  | {
      // v0.27.0 — api.worldInfo.registerInterceptor() handler. Same
      // child-generates-handlerId pattern as macroInterceptor +
      // contentProcessor: the parent forwards via `options.id = handlerId`
      // to `addEntry` so the handle's `.id` returned synchronously to
      // user code matches what's stored parent-side.
      type:      'register-handler';
      kind:      'worldInfoInterceptor';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      options?:  WorldInfoInterceptorOptions;
      hasHandler: true;
    }
  | {
      // v1.4 — api.chat.onMessageTag() message-tag interceptor. `tagName` is the
      // tag to intercept; `options` carries attrs + removeFromMessage. Same
      // child-generates-handlerId pattern as worldInfoInterceptor.
      type:      'register-handler';
      kind:      'messageTagHandler';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      tagName:   string;
      options?:  MessageTagOptions;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'domEventListener';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      // Carries the elementId of the DOMHandle the listener attaches to.
      // Parent looks up the canonical handle in `pendingDomHandles` by
      // (scriptId, elementId) and calls `canonicalHandle.on(event, wrapper, options)`.
      elementId: string;
      event:     string;
      options?:  DOMListenOptions;
      hasHandler: true;
    }
  | {
      // v0.27.1 — api.ui.dom.delegate() handler. Unlike `domEventListener`
      // (which attaches to a specific script-injected DOMHandle), delegate
      // installs a CAPTURE-PHASE listener at a known root (chat container
      // or document) and matches descendants by CSS selector. Used to react
      // to events on DOM the script DIDN'T inject — primarily LLM-emitted
      // interactive elements inside `.mes_text` content.
      //
      // No `elementId` — the host's frontend manages the (root, event)
      // listener registry independently from per-script DOM handles. The
      // child generates the `handlerId` and the parent forwards it to the
      // frontend's delegation registry; on match, the frontend posts a
      // `dom-delegate-fired` notice carrying handlerId + serialized event
      // data, which the host routes back through `sendRunHandlerRequest`.
      type:      'register-handler';
      kind:      'domDelegate';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      selector:  string;
      event:     string;
      options?:  DOMDelegateOptions;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'inputBarActionClick';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      // Carries the actionId of the InputBarActionHandle the listener attaches to.
      // Parent looks up the canonical handle in `pendingInputBarActions` by
      // (scriptId, actionId) and calls `canonicalHandle.onClick(wrapper)`,
      // storing the returned unsub fn under handlerId in `handlerCleanups`.
      // Same shape as `domEventListener` minus the event-name / options
      // fields (input-bar click is a single event with no options).
      actionId:  string;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'floatWidgetDragEnd';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      // Carries the widgetId of the FloatWidgetHandle the listener attaches to.
      // Parent looks up the canonical handle in `pendingFloatWidgets` by
      // (scriptId, widgetId) and calls `canonicalHandle.onDragEnd(wrapper)`,
      // storing the returned unsub fn under handlerId in `handlerCleanups`.
      //
      // Wrapper signature on parent: `(pos: {x,y}) => void`. Each fire emits
      // `RunHandlerRequest` with args=[pos]. Child closure invokes user fn
      // with `pos` as first arg.
      //
      // Position-cache sync is independent of this register-handler path:
      // the parent fires a `FloatWidgetPositionNotice` to the child once
      // per drag (regardless of how many user handlers are registered) so
      // the child's positionCache stays accurate even with zero handlers.
      widgetId:  string;
      hasHandler: true;
    }
  | {
      type:      'register-handler';
      kind:      'drawerTabActivate';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      // Carries the tabId of the DrawerTabHandle the listener attaches to.
      // Parent looks up the canonical handle in `pendingDrawerTabs` by
      // (scriptId, tabId) and calls `canonicalHandle.onActivate(wrapper)`,
      // storing the returned unsub fn under handlerId in `handlerCleanups`.
      // Same shape as `inputBarActionClick` (no event-name / payload —
      // tab activation is a single event with no args).
      tabId:     string;
      hasHandler: true;
    }
  | {
      // v1.0.0-rc.5 — api.oauth.onCallback() handler registration.
      // No extra payload — the host stores the callback handler in a
      // single module-scope ref (one slot per extension). Parent's
      // handler wraps `spindle.oauth.onCallback(wrapper)`, where the
      // wrapper fires `sendRunHandlerRequest(scriptId, handlerId,
      // 'oauthCallback', [params], …)` and forwards the handler-result's
      // value (`{html?: string} | undefined`) back to the host's
      // callback API. Unsubscribe drops the parent's registration via
      // the canonical's returned unsub fn, stored in handlerCleanups.
      //
      // Cross-script + same-script-re-register collisions surface as
      // `spindle.log.warn` from the parent's `case 'oauthCallback'`
      // branch — non-terminating, behaviour matches the host's
      // last-wins semantics.
      type:      'register-handler';
      kind:      'oauthCallback';
      runId:     string;
      scriptId:  string;
      handlerId: string;
      hasHandler: true;
    };

/**
 * Phase 9d.3 — child unregistering a function-handler. Two paths:
 *   - `name`-based (e.g. `api.macros.unregister(name)`): parent looks up
 *     the wrapper by `(scriptId, name, kind)` in its store.
 *   - `handlerId`-based (e.g. `handle.remove()` returned by
 *     `chat.registerContentProcessor` etc.): parent looks up by
 *     `(scriptId, handlerId)` in its handler-id table.
 *
 * Either field may be supplied; the parent prefers `handlerId` when both
 * are present (it's unambiguous for handle-based registrations).
 */
export interface UnregisterHandler {
  type:       'unregister-handler';
  kind:       HandlerKind;
  scriptId:   string;
  handlerId?: string;
  name?:      string;
}

/**
 * Child reporting the lifecycle of an async broadcast handler so the host
 * can keep `executionStatusStore` in sync with what the user's script is
 * actually doing.
 *
 * Sent by `handleBroadcastFire` in the child when the user-registered
 * broadcast handler returns a thenable. The host updates the sidebar
 * status indicator (markRunning → markSuccess / markError) for the
 * owning script across the duration of the awaited work.
 *
 * Sync handlers (those that don't return a thenable) produce no messages
 * — the indicator simply doesn't update for that handler. Same for
 * sync-throwing handlers (caught locally, no Promise to track).
 *
 * Cross-talk with the trigger-registry's `runningCounts`: the host's
 * status update from this notice is independent of trigger-registry's
 * concurrent-invocation counter. If a trigger run AND a broadcast
 * handler are both in flight for the same script, the dot may briefly
 * flash green when the broadcast finishes before the trigger does.
 * Tolerable for v1; a future refactor could share the counter if needed.
 */
export type BroadcastHandlerLifecycleNotice =
  | {
      type:      'broadcast-handler-started';
      scriptId:  string;
      subId:     string;
      event:     string;
    }
  | {
      type:      'broadcast-handler-finished';
      scriptId:  string;
      subId:     string;
      event:     string;
      durationMs: number;
      ok:        true;
    }
  | {
      type:       'broadcast-handler-finished';
      scriptId:   string;
      subId:      string;
      event:      string;
      durationMs: number;
      ok:         false;
      error:      string;
    };

/**
 * Child's response to a `DiagnosticStatsRequest`. Carries a snapshot of
 * the child process's resource usage at the moment of receipt. Numbers
 * map to standard Node-compat `process.memoryUsage()` /
 * `process.cpuUsage()` outputs (bytes and microseconds respectively).
 *
 * Both APIs are standard Bun/Node introspection — no banned-API
 * concern in the post-security-overhaul Lumiverse world.
 */
export interface DiagnosticStatsResponse {
  type:      'diagnostic-stats-response';
  requestId: string;
  /** Resident set size in bytes (`process.memoryUsage().rss`). */
  rss:       number;
  /** Total heap size in bytes (`heapTotal`). */
  heapTotal: number;
  /** Heap actively used in bytes (`heapUsed`). */
  heapUsed:  number;
  /** External memory in bytes (typed array buffers, etc.). */
  external:  number;
  /** Cumulative user-mode CPU time in microseconds. */
  cpuUserUs:   number;
  /** Cumulative system-mode CPU time in microseconds. */
  cpuSystemUs: number;
  /** Process uptime in seconds. */
  uptimeSec: number;
}

export type ChildToParentMessage =
  | ScriptRunningNotice
  | RunScriptResult
  | ApiProxyRequest
  | AbortRequest
  | StreamRequest
  | StreamCancelRequest
  | BroadcastSubscribeMessage
  | BroadcastUnsubscribeMessage
  | BroadcastHandlerLifecycleNotice
  | ConsoleEntryNotice
  | RegisterHandler
  | UnregisterHandler
  | DiagnosticStatsResponse
  | HandlerResult;

// ─── Type guards ────────────────────────────────────────────────────────────

/**
 * Narrow check for whether an arbitrary value looks like a `HandleRef`.
 * Useful in dispatcher / proxy code that walks args or return values
 * looking for handle-shaped objects to translate.
 *
 * Intentionally structural — doesn't import the type, so it survives
 * cross-bundle boundaries cleanly.
 */
export function isHandleRef(value: unknown): value is HandleRef {
  return (
    typeof value === 'object' &&
    value !== null &&
    (value as { __handleRef?: unknown }).__handleRef === true &&
    typeof (value as { id?: unknown }).id === 'string' &&
    typeof (value as { kind?: unknown }).kind === 'string'
  );
}
