/**
 * #11 P3 B — generate the in-VM library bundles for the QuickJS engine.
 *
 * The QuickJS isolate has no module system, so libraries that user scripts use
 * as VM globals (currently `z` / zod) must be bundled into a self-contained IIFE
 * that assigns to `globalThis`, then eval'd into the context. This script
 * bundles each `scripts/vm-libs/*-entry.ts` into such an IIFE and emits it as a
 * string constant under `src/script-runner/generated/` (committed + regenerated
 * by the build chain, mirroring the gen:corpus pattern). qjs-engine.ts evals the
 * constant once per context.
 *
 * Run via `bun run gen:vm-libs` (chained into `bun run build` before typecheck).
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT_DIR = join('src', 'script-runner', 'generated');

interface VmLib { entry: string; out: string; constName: string; label: string; }

const LIBS: VmLib[] = [
  {
    entry:     join('scripts', 'vm-libs', 'zod-entry.ts'),
    out:       'vm-zod-bundle.ts',
    constName: 'VM_ZOD_BUNDLE',
    label:     'zod',
  },
  {
    entry:     join('scripts', 'vm-libs', 'handlebars-entry.ts'),
    out:       'vm-handlebars-bundle.ts',
    constName: 'VM_HANDLEBARS_BUNDLE',
    label:     'handlebars',
  },
];

await mkdir(OUT_DIR, { recursive: true });

for (const lib of LIBS) {
  const result = await Bun.build({
    entrypoints: [lib.entry],
    format:      'iife',     // self-contained; no top-level import/export (eval-able in QuickJS)
    minify:      true,
    target:      'browser',  // closest to QuickJS — no node builtins
  });
  if (!result.success) {
    console.error(`[vm-libs] FAILED to bundle ${lib.label}:`);
    for (const log of result.logs) console.error('  ', log);
    process.exit(1);
  }
  const code = await result.outputs[0]!.text();
  // Sanity: a stray top-level import/export would make QuickJS reject the eval.
  if (/^\s*(import|export)\b/m.test(code)) {
    console.error(`[vm-libs] ${lib.label}: bundle has a top-level import/export — not eval-able in QuickJS.`);
    process.exit(1);
  }
  const file = join(OUT_DIR, lib.out);
  const banner =
    `// GENERATED by scripts/build-vm-libs.ts — DO NOT EDIT.\n` +
    `// Bundled ${lib.label} as a self-contained IIFE for the QuickJS VM (#11 P3 B).\n` +
    `// Regenerate with \`bun run gen:vm-libs\` after upgrading ${lib.label}.\n`;
  await writeFile(file, `${banner}export const ${lib.constName} = ${JSON.stringify(code)};\n`, 'utf8');
  console.log(`[vm-libs] Wrote ${file}  (${lib.label}: ${(code.length / 1024).toFixed(0)} KB)`);
}

console.log('[vm-libs] Done.');
