/**
 * Generates `src/types/editor-lib.ts` — the Monaco IntelliSense mirror of the
 * script-facing `api.*` surface, registered into the editor via `addExtraLib`.
 *
 * The `api`/`script` TYPE surface is rolled up from `src/types/script.ts` (the
 * frozen contract) by dts-bundle-generator, so the editor's hints can never drift
 * from what scripts actually receive. The genuinely editor-only overlay — the
 * minimal Zod shim, the `ls:*` library `require()` overloads, and the ambient
 * globals — lives in `scripts/editor-lib-fragments/` and is concatenated around
 * the generated bulk. Output is emitted through a template literal with all
 * backticks / `${` deterministically escaped (no more manual backtick trap).
 *
 * Wired into `bun run build` via `gen:editor-lib`, ahead of the typechecks —
 * same pattern as `gen:corpus`.
 */
import { generateDtsBundle } from 'dts-bundle-generator';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT  = join(import.meta.dir, '..');
const ENTRY = join(ROOT, 'src/types/editor-lib-entry.ts');
const FRAG  = join(ROOT, 'scripts/editor-lib-fragments');
// Env override lets Phase-2 write to a scratch file for diffing before the flip.
const OUT   = process.env.EDITOR_LIB_OUT ?? join(ROOT, 'src/types/editor-lib.ts');

// 1. Roll up the transitive .d.ts closure of the curated entry. `inlinedLibraries`
//    pulls the lumiverse-spindle-types host DTOs in-bundle (no dangling import the
//    editor can't resolve); `exportReferencedTypes:false` keeps referenced types as
//    bare declarations, matching a non-module .d.ts.
const bundles = generateDtsBundle(
  [
    {
      filePath: ENTRY,
      libraries: { inlinedLibraries: ['lumiverse-spindle-types'] },
      output: { noBanner: true, exportReferencedTypes: false, sortNodes: false },
    },
  ],
  { preferredConfigPath: join(ROOT, 'tsconfig.json') },
);
const rawBundle = bundles[0];
if (rawBundle === undefined) throw new Error('[gen-editor-lib] dts-bundle-generator produced no output');

// 2. Strip module syntax → bare ambient declarations. Monaco's addExtraLib wants a
//    NON-module .d.ts so every type is globally in scope in the editor (a single
//    `export` would make it a module and hide the types behind imports).
const bulk = rawBundle
  .replace(/^export declare /gm, 'declare ')
  .replace(/^export (interface|type|const|function|namespace|enum|class|abstract) /gm, '$1 ')
  .replace(/^\s*export \{[^}]*\};?\s*$/gm, '') // `export { A, B };` re-export lines
  .replace(/^\s*import[^\n]*\n/gm, '')          // any residual import lines
  .replace(/^\s*export \{\};?\s*$/gm, '')       // empty `export {}`
  .trim();

// 3. Hand-authored overlay fragments (editor-only: the Zod shim, ScriptNamespace +
//    its ls:* require overloads, and the ambient `declare const` globals). The file
//    numbers mirror the assembled layout in step 4 below — 01 zod / [02 = the
//    generated `bulk`, which has no file] / 03 script+ls / 04 globals — which is why
//    there is intentionally no `02-*.d.ts`.
const readFrag = (f: string) => readFileSync(join(FRAG, f), 'utf8').trim();
const zod      = readFrag('01-zod-shim.d.ts');
const scriptLs = readFrag('03-script-and-ls.d.ts');
const globals  = readFrag('04-globals.d.ts');

// 4. Assemble (order is cosmetic — a .d.ts is a type space, not sequential).
const assembled = [zod, bulk, scriptLs, globals].join('\n\n');

// 5. Escape for the template literal (backslash FIRST so we don't double-escape).
const escaped = assembled
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const header = [
  '/**',
  ' * AUTO-GENERATED by scripts/gen-editor-lib.ts — DO NOT EDIT BY HAND.',
  ' *',
  ' * The api/script type surface is rolled up from src/types/script.ts (the frozen',
  ' * contract) so the editor can never drift from what scripts receive. The Zod',
  ' * shim, ls:* library overloads, and ambient globals come from',
  ' * scripts/editor-lib-fragments/. Regenerate with:  bun run gen:editor-lib',
  ' * (wired into bun run build, ahead of the typechecks).',
  ' */',
  '',
  '/** @internal Monaco ambient declarations for the script editor (addExtraLib). */',
  'export const LUMISCRIPT_DEFS = `',
].join('\n');

const file = `${header}\n${escaped}\n\`;\n`;
writeFileSync(OUT, file);

console.log(`[gen-editor-lib] wrote ${OUT}`);
console.log(`[gen-editor-lib]   generated bulk: ${bulk.split('\n').length} lines`);
console.log(`[gen-editor-lib]   overlay: zod ${zod.split('\n').length} + script/ls ${scriptLs.split('\n').length} + globals ${globals.split('\n').length}`);
console.log(`[gen-editor-lib]   total: ${file.split('\n').length} lines`);
